import Head from 'next/head'
import Navbar from '../components/Navbar'
import Main from '../components/Main'
import Skills from '../components/Skills'
import Proyects from '../components/Projects'
import Contact from '../components/Contact'
import PageFooter from '../components/Footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title> Carlos | Developer </title>
        <meta name="description" content="Generated by create next app" />
        </Head>
      <Navbar />
      <Main />
      <Skills />
      <Proyects />
      <Contact />
      <PageFooter />
    </div>
  )
}
